# Generated by Django 5.2 on 2025-04-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panier',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('validé', 'Validé'), ('termine', 'Terminé')], default='actif', max_length=20),
        ),
    ]
