# Generated by Django 5.2 on 2025-04-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_panier_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='delivery_method',
            field=models.CharField(choices=[('livraison', 'Livraison à domicile'), ('emporter', 'À emporter')], default='emporter', max_length=20),
        ),
        migrations.AddField(
            model_name='commande',
            name='payment_method',
            field=models.CharField(choices=[('wave', 'Wave'), ('orange_money', 'Orange Money')], default='wave', max_length=20),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('preparation', 'Préparation'), ('livreur', 'Livreur'), ('prete', 'Commande Prête')], default='preparation', max_length=20),
        ),
        migrations.AlterField(
            model_name='commande',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
